# Preparation

In [ ]:
import pandas as pd
df = pd.read_csv('../data/raw/ulasan_dana.csv')

# Data Analysis

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740000 entries, 0 to 739999
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   reviewId              740000 non-null  object
 1   userName              740000 non-null  object
 2   userImage             740000 non-null  object
 3   content               739999 non-null  object
 4   score                 740000 non-null  int64
 5   thumbsUpCount         740000 non-null  int64
 6   reviewCreatedVersion  605800 non-null  object
 7   at                    740000 non-null  object
 8   replyContent          417389 non-null  object
 9   repliedAt             417389 non-null  object
 10  appVersion            605800 non-null  object
dtypes: int64(2), object(9)
memory usage: 62.1+ MB

In [7]:
df.duplicated().sum()

0

In [8]:
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8c382ad2-2c81-436e-a18e-87be3fdcc662,Hermansyah Radin,https://play-lh.googleusercontent.com/a/ACg8oc...,ok,5,0,NaN,2026-01-22 09:14:57,NaN,NaN,NaN
1,47553db5-9026-4233-8bf7-8449e550da69,Zidni Cell,https://play-lh.googleusercontent.com/a-/ALV-U...,bagus,5,0,NaN,2026-01-22 09:11:52,NaN,NaN,NaN
2,9a1a84ba-1b7d-4010-a58d-1f373b280082,Akhi Sondi,https://play-lh.googleusercontent.com/a-/ALV-U...,mantulll pokok eh,5,0,2.110.0,2026-01-22 09:11:39,NaN,NaN,2.110.0
3,0460a39e-7580-44bf-8a79-8446fb2414eb,Yati Yati,https://play-lh.googleusercontent.com/a/ACg8oc...,mempermudah,5,0,2.110.0,2026-01-22 09:09:57,NaN,NaN,2.110.0
4,b461e228-9033-4bea-b835-322d0db38fc2,Joker 16,https://play-lh.googleusercontent.com/a/ACg8oc...,mantap,5,0,2.111.0,2026-01-22 09:09:34,NaN,NaN,2.111.0

# Data Modification

In [ ]:
kolom_dibuang = ['userImage', 'reviewCreatedVersion', 'replyContent', 'repliedAt']
df.drop(columns=kolom_dibuang, inplace=True, errors='ignore')

In [ ]:
df.rename(columns={
    'reviewId': 'id_ulasan',
    'userName': 'user',
    'content': 'ulasan',
    'score': 'rating',
    'thumbsUpCount': 'dukungan_ulasan',
    'at': 'tanggal',
    'appVersion': 'versi_aplikasi'
}, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740000 entries, 0 to 739999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_ulasan        740000 non-null  object
 1   user             740000 non-null  object
 2   ulasan           739999 non-null  object
 3   rating           740000 non-null  int64
 4   dukungan_ulasan  740000 non-null  int64
 5   tanggal          740000 non-null  object
 6   versi_aplikasi   605800 non-null  object
dtypes: int64(2), object(5)
memory usage: 39.5+ MB

In [ ]:
df['tanggal'] = pd.to_datetime(df['tanggal'])
df['versi_aplikasi'] = df['versi_aplikasi'].astype('category')
print(df.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740000 entries, 0 to 739999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_ulasan        740000 non-null  object
 1   user             740000 non-null  object
 2   ulasan           739999 non-null  object
 3   rating           740000 non-null  int64
 4   dukungan_ulasan  740000 non-null  int64
 5   tanggal          740000 non-null  datetime64[ns]
 6   versi_aplikasi   605800 non-null  category
dtypes: category(1), datetime64[ns](1), int64(2), object(3)
memory usage: 217.8 MB
None

In [12]:
df.head()

,id_ulasan,user,ulasan,rating,dukungan_ulasan,tanggal,versi_aplikasi
0,8c382ad2-2c81-436e-a18e-87be3fdcc662,Hermansyah Radin,ok,5,0,2026-01-22 09:14:57,NaN
1,47553db5-9026-4233-8bf7-8449e550da69,Zidni Cell,bagus,5,0,2026-01-22 09:11:52,NaN
2,9a1a84ba-1b7d-4010-a58d-1f373b280082,Akhi Sondi,mantulll pokok eh,5,0,2026-01-22 09:11:39,2.110.0
3,0460a39e-7580-44bf-8a79-8446fb2414eb,Yati Yati,mempermudah,5,0,2026-01-22 09:09:57,2.110.0
4,b461e228-9033-4bea-b835-322d0db38fc2,Joker 16,mantap,5,0,2026-01-22 09:09:34,2.111.0

In [13]:
df.isnull().sum()

id_ulasan               0
user                    0
ulasan                  1
rating                  0
dukungan_ulasan         0
tanggal                 0
versi_aplikasi     134200
dtype: int64

In [ ]:
print(df[df['ulasan'].isna()])

                                   id_ulasan      user ulasan  rating  \
644012  b9281a11-20b4-48c0-a7ba-f7d825212ee6  mas nDra    NaN       1

        dukungan_ulasan             tanggal versi_aplikasi
644012                0 2024-03-22 11:20:22         2.53.1

In [ ]:
df['ulasan'] = df['ulasan'].fillna('no review')
print(f"Jumlah missing values sekarang: {df['ulasan'].isna().sum()}")
print("\nCek ulasan yang baru diisi:")
df[df['ulasan'] == 'no review']

Jumlah missing values sekarang: 0

Cek ulasan yang baru diisi:

,id_ulasan,user,ulasan,rating,dukungan_ulasan,tanggal,versi_aplikasi
644012,b9281a11-20b4-48c0-a7ba-f7d825212ee6,mas nDra,no review,1,0,2024-03-22 11:20:22,2.53.1

In [ ]:
df['versi_aplikasi'] = df['versi_aplikasi'].cat.add_categories(['unknown']).fillna('unknown')
df[df['versi_aplikasi'] == 'unknown']

,id_ulasan,user,ulasan,rating,dukungan_ulasan,tanggal,versi_aplikasi
0,8c382ad2-2c81-436e-a18e-87be3fdcc662,Hermansyah Radin,ok,5,0,2026-01-22 09:14:57,unknown
1,47553db5-9026-4233-8bf7-8449e550da69,Zidni Cell,bagus,5,0,2026-01-22 09:11:52,unknown
9,f0f79437-2efe-4574-99b2-0f3fb28df85b,aspar konami98,sangat memuaskan pake aplikasi dana,5,0,2026-01-22 09:00:42,unknown
10,922d0d3f-6ee3-42d6-83ad-8a2fa85dd9b9,Erik setiawan,sangar bagus,5,0,2026-01-22 08:59:18,unknown
25,3e474767-d552-4bd3-9ffc-9702d9a8f9bb,Deby Nuraeni,saya buka aplikasi dana kok malah enggak bisa ...,5,0,2026-01-22 08:30:46,unknown
...,...,...,...,...,...,...,...
739974,76c1df92-bd0a-4dc0-8fcd-52ee73a0d21c,Tiru Tiru,Mau pinjam uang,5,0,2023-12-31 08:28:31,unknown
739976,26080c7a-e032-402a-a1f5-44468a7a16f4,Hollpi Nrcos,Sangat bagus,5,0,2023-12-31 08:27:07,unknown
739985,65716b94-e5af-444f-83e8-faeefd97d0bb,Monica Debora Official,Aplikasi jelek dan gak aman . Ga bisa login pa...,1,0,2023-12-31 08:17:45,unknown
739986,ad454d48-eb2c-4995-b9ea-fe8a53ca88bc,Cup DsiGen,Aplikasi ini sangat bagus dan fitur lainya bis...,5,0,2023-12-31 08:17:17,unknown
739998,4ee47e23-f6d2-4b84-b81b-54896d3dbad5,Christofel daniel,Gagal mulu,1,0,2023-12-31 07:54:25,unknown

In [17]:
df.isnull().sum()

id_ulasan          0
user               0
ulasan             0
rating             0
dukungan_ulasan    0
tanggal            0
versi_aplikasi     0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740000 entries, 0 to 739999
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_ulasan        740000 non-null  object
 1   user             740000 non-null  object
 2   ulasan           740000 non-null  object
 3   rating           740000 non-null  int64
 4   dukungan_ulasan  740000 non-null  int64
 5   tanggal          740000 non-null  datetime64[ns]
 6   versi_aplikasi   740000 non-null  category
dtypes: category(1), datetime64[ns](1), int64(2), object(3)
memory usage: 35.3+ MB

# Save Cleaned Data

In [ ]:
df.to_parquet('../data/cleaned/ulasan_dana_cleaned.parquet')