In [32]:
import pandas as pd

# Baca Data Raw

In [ ]:
raw_df = pd.read_csv('../frequency_dictionary_id.csv')
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16606 entries, 0 to 16605
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   kata       16604 non-null  object
 1   frekuensi  16606 non-null  int64
dtypes: int64(1), object(1)
memory usage: 259.6+ KB

In [ ]:
raw_df.head(5)

          kata  frekuensi
0        bagus      81252
1     mantulll         88
2        pokok        903
3  mempermudah       3575
4       mantap      45450
5      setelah       5119
6       update      10354
7        malah      18422
8          gak      41162
9         bisa     105497

In [ ]:
raw_df.tail(5)

                  kata  frekuensi
16596            obing          6
16597        disiapkan          6
16598        peroteksi          6
16599         duplikat          5
16600              kup          5
16601            jazah          6
16602       penghubung          5
16603  xxxxxxcxxcxxxxx         15
16604              taw          5
16605         youngjoy          5

In [ ]:
df_sorted = raw_df.sort_values(by="frekuensi", ascending=False)
df_sorted.head(20)
df_sorted.to_csv('../frequency_dictionary_id_sorted.csv', index=False)

# Data Hasil Shorted

In [60]:
df = pd.read_csv('../frequency_dictionary_id_sorted.csv')
df.head(10)

       kata  frekuensi koreksi
0      dana     195304     NaN
1      saya     156740     NaN
2    sangat     109875     NaN
3      bisa     105497     NaN
4     tidak      81385     NaN
5     bagus      81252     NaN
6       dan      73414     NaN
7       ada      72243     NaN
8       nya      68114     NaN
9  aplikasi      63019     NaN

In [61]:
df["kata_final"] = df["koreksi"].replace("", pd.NA).fillna(df["kata"])

In [64]:
df.head(20)

         kata  frekuensi koreksi kata_final
0        dana     195304     NaN       dana
1        saya     156740     NaN       saya
2      sangat     109875     NaN     sangat
3        bisa     105497     NaN       bisa
4       tidak      81385     NaN      tidak
5       bagus      81252     NaN      bagus
6         dan      73414     NaN        dan
7         ada      72243     NaN        ada
8         nya      68114     NaN        nya
9    aplikasi      63019     NaN   aplikasi
10        ini      60674     NaN        ini
11   membantu      55215     NaN   membantu
12      saldo      47716     NaN      saldo
13     mantap      45450     NaN     mantap
14  transaksi      44730     NaN  transaksi
15       uang      42185     NaN       uang
16        gak      41162   tidak      tidak
17      sudah      39126     NaN      sudah
18       akun      37373     NaN       akun
19       tapi      35338     NaN       tapi

In [67]:
# pakai hanya kolom yang dibutuhkan
df_final = df[["kata_final", "frekuensi"]].copy()
# rename kolom
df_final = df_final.rename(columns={"kata_final": "kata"})

# simpan ke file baru
df_final.to_csv("../data/kamus/frequency_dictionary_cleaned.csv", index=False)

In [ ]:
# mapping = dict(zip(df["kata"], df["kata_final"]))

# def apply_correction(text):
#     words = text.split()
#     corrected = [mapping.get(word, word) for word in words]
#     return " ".join(corrected)

In [ ]:
# top500 = df_sorted.head(500)
# top500.tail(20)

# Prepocessing KBBI

In [53]:
# pip install Sastrawi
# %pip install kbbi

In [ ]:
# from kbbi import KBBI
# from kbbi import TidakDitemukan

# def is_in_kbbi(word):
#     try:
#         KBBI(word)
#         return "ada"
#     except TidakDitemukan:
#         return "tidak ada"
#     except Exception as e:
#         return "error"

In [ ]:
# df_top = df.sort_values("frekuensi", ascending=False)#.head(3000)
# df_top["is_in_kbbi"] = df_top["kata"].apply(is_in_kbbi)

In [ ]:
# not_standard = df_top[df_top["is_in_kbbi"] == False]
# print(not_standard.tail(10))

Empty DataFrame
Columns: [kata, frekuensi, cek_kbbi, is_in_kbbi]
Index: []

In [ ]:
# df["cek_kbbi"] = df["kata"].apply(is_in_kbbi)

In [ ]:
# df.to_csv("kata_kbbi_check.csv", index=False)

# Cek File CSV KBBI

In [ ]:
# df = pd.read_csv('kata_kbbi_check.csv')
# df.head(10)

       kata  frekuensi cek_kbbi
0      dana     195304    error
1      saya     156740    error
2    sangat     109875    error
3      bisa     105497    error
4     tidak      81385    error
5     bagus      81252    error
6       dan      73414    error
7       ada      72243    error
8       nya      68114    error
9  aplikasi      63019    error